# Generated by Django 5.2.18 on 2026-10-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "ámbito",
                "verbose_name_plural": "ámbitos",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("identificador", models.SlugField(max_length=100, unique=True)),
                (
                    "destino",
                    models.SlugField(
                        help_text="Identificador del nodo. No es clave foránea: es inmutable.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "alias",
                "verbose_name_plural": "alias",
                "ordering": ["identificador"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("identificador", models.F("destino")), _negated=True),
                        name="alias_distinto_de_destino",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Nodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "identificador",
                    models.SlugField(help_text="Inmutable.", max_length=100, unique=True),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=30)),
                (
                    "clase",
                    models.CharField(
                        choices=[("intercambio", "Intercambio"), ("plataforma", "Plataforma")],
                        max_length=20,
                    ),
                ),
                (
                    "intercambio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consulta", "El municipio consulta"),
                            ("entrega", "El municipio entrega"),
                        ],
                        help_text="Vacío si es una plataforma.",
                        max_length=20,
                    ),
                ),
                ("funcion", models.TextField(verbose_name="función")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "madurez",
                    models.CharField(
                        choices=[
                            ("Deseable", "Deseable"),
                            ("En evaluación", "En Evaluacion"),
                            ("En desarrollo", "En Desarrollo"),
                            ("Operativo", "Operativo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instituciones",
                    models.JSONField(default=list, help_text="Lista de nombres, como en la ficha."),
                ),
                ("responsable_organismo", models.CharField(max_length=200)),
                ("responsable_equipo", models.CharField(blank=True, max_length=200)),
                ("responsable_correo", models.EmailField(max_length=254)),
                ("origen_norma", models.TextField(blank=True)),
                ("origen_nota", models.TextField(blank=True)),
                (
                    "procedencia_copia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exacta", "Copia exacta"),
                            ("instantanea", "Instantánea"),
                            ("reconstruccion", "Reconstrucción"),
                            ("sin-copia", "Sin copia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("procedencia_fuente", models.TextField(blank=True)),
                ("procedencia_detalle", models.TextField(blank=True)),
                (
                    "acceso_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abierto", "Abierto"),
                            ("credencial", "Con credencial"),
                            ("clave-unica", "Con Clave Única"),
                        ],
                        max_length=20,
                    ),
                ),
                ("acceso_detalle", models.TextField(blank=True)),
                ("leido_en", models.DateTimeField(verbose_name="leído en")),
                (
                    "commit",
                    models.CharField(
                        blank=True,
                        help_text="Vacío: carga manual, sin fuente verificable.",
                        max_length=64,
                    ),
                ),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[
                            ("publicado", "Publicado"),
                            ("oculto", "Oculto"),
                            ("retirado", "Retirado"),
                        ],
                        default="oculto",
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("nota_editorial", models.TextField(blank=True)),
                (
                    "ambito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodos",
                        to="catalogo.ambito",
                    ),
                ),
            ],
            options={
                "verbose_name": "nodo",
                "verbose_name_plural": "nodos",
                "ordering": ["ambito__orden", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Especificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=50, verbose_name="versión")),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("openapi-3.0", "OpenAPI 3.0"),
                            ("openapi-3.1", "OpenAPI 3.1"),
                            ("descripcion", "Solo metadato"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ruta",
                    models.CharField(
                        blank=True,
                        help_text="Dentro del repositorio. Vacía: solo metadato.",
                        max_length=300,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(blank=True, help_text="El archivo tal como se leyó."),
                ),
                (
                    "huella",
                    models.CharField(blank=True, help_text="sha256 del contenido.", max_length=64),
                ),
                ("publicada", models.DateField(blank=True, null=True)),
                ("vigente", models.BooleanField(default=False)),
                ("commit", models.CharField(blank=True, max_length=64)),
                (
                    "nodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="especificaciones",
                        to="catalogo.nodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "especificación",
                "verbose_name_plural": "especificaciones",
                "ordering": ["nodo", "-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nodo", "version"), name="especificacion_version_unica"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("vigente", True)),
                        fields=("nodo",),
                        name="una_especificacion_vigente",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Ambiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        choices=[("pruebas", "Pruebas"), ("produccion", "Producción")],
                        max_length=20,
                    ),
                ),
                ("base", models.URLField(max_length=500)),
                (
                    "datos",
                    models.CharField(
                        choices=[("inventados", "Inventados"), ("reales", "Reales")], max_length=20
                    ),
                ),
                (
                    "nodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambientes",
                        to="catalogo.nodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ambiente",
                "verbose_name_plural": "ambientes",
                "ordering": ["nodo", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nodo", "nombre"), name="ambiente_unico_por_nodo"
                    )
                ],
            },
        ),
    ]
