# Generated by Django 5.2.18 on 2026-10-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(help_text="Inmutable.", max_length=100, unique=True)),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Para el índice.", max_length=300, verbose_name="descripción"
                    ),
                ),
                (
                    "nodo",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador del nodo. No es clave foránea.",
                        max_length=100,
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usar_el_nodo", "Usar el nodo"),
                            ("intercambios", "Intercambios"),
                            ("codigos", "Códigos y datos maestros"),
                            ("normas", "Marco normativo"),
                            ("referencia", "Referencia"),
                        ],
                        max_length=20,
                        verbose_name="sección",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "entrada",
                "verbose_name_plural": "entradas",
                "ordering": ["seccion", "orden", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("markdown", models.TextField()),
                (
                    "resumen",
                    models.CharField(help_text="Qué cambió, para el historial.", max_length=300),
                ),
                ("publicada", models.BooleanField(default=False)),
                ("publicada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nulo: contenido inicial, transcrito desde la maqueta.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones_wiki",
                        to="cuentas.perfil",
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones",
                        to="wiki.entrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión",
                "verbose_name_plural": "versiones",
                "ordering": ["entrada", "-creado_en", "-id"],
            },
        ),
        migrations.AddField(
            model_name="entrada",
            name="vigente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wiki.version",
            ),
        ),
    ]
