/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ambitos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ambitos_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fuentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Las fuentes registradas. Registrar una la lee en el acto, aunque la lectura falle. */
        get: operations["fuentes_listar"];
        put?: never;
        /** @description Las fuentes registradas. Registrar una la lee en el acto, aunque la lectura falle. */
        post: operations["fuentes_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fuentes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cambiar la dirección es el traspaso de custodia; `activa: false`, dar de baja la fuente. */
        get: operations["fuentes_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Cambiar la dirección es el traspaso de custodia; `activa: false`, dar de baja la fuente. */
        patch: operations["fuentes_modificar"];
        trace?: never;
    };
    "/api/v1/fuentes/{id}/lecturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El historial de lecturas de una fuente, de la más reciente a la más antigua. */
        get: operations["fuentes_lecturas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fuentes/{id}/sincronizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Vuelve a leer ahora. Responde con la lectura, válida o no. */
        post: operations["fuentes_sincronizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Las 346 comunas con su código CUT, de `core.Municipio`. */
        get: operations["municipios_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios/{cut}/encargado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Designa o reemplaza al encargado. El anterior queda como perfil común de su municipio. */
        put: operations["municipios_designar_encargado"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios/{cut}/equipo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El equipo de un municipio. El RUN, solo para quien lo administra. */
        get: operations["municipios_equipo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El catálogo. Sin sesión, solo lo publicado. */
        get: operations["nodos_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodos/{identificador}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description La ficha de un nodo. La lee cualquiera si está publicado; la edita un curador. */
        get: operations["nodos_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description La ficha de un nodo. La lee cualquiera si está publicado; la edita un curador. */
        patch: operations["nodos_editar"];
        trace?: never;
    };
    "/api/v1/nodos/{identificador}/especificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description La especificación vigente del nodo, con las mismas reglas de visibilidad que el nodo. */
        get: operations["nodos_especificacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodos/{identificador}/especificacion/archivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El archivo tal como se leyó del repositorio, byte por byte. */
        get: operations["nodos_especificacion_archivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administradores: todos los perfiles. Encargados: los de su municipio. */
        get: operations["perfiles_listar"];
        put?: never;
        /** @description Administradores: todos los perfiles. Encargados: los de su municipio. */
        post: operations["perfiles_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Los perfiles no se borran: se desactivan con `activo: false`. */
        get: operations["perfiles_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Los perfiles no se borran: se desactivan con `activo: false`. */
        patch: operations["perfiles_modificar"];
        trace?: never;
    };
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Responde si la API está arriba. Sin detalles de infraestructura ni de la base. */
        get: operations["salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Los servicios de nodos publicados, o los de un nodo. Los crea un curador. */
        get: operations["servicios_listar"];
        put?: never;
        /** @description Los servicios de nodos publicados, o los de un nodo. Los crea un curador. */
        post: operations["servicios_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servicios/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Un servicio. Si su nodo no está publicado, solo con sesión. */
        get: operations["servicios_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Un servicio. Si su nodo no está publicado, solo con sesión. */
        patch: operations["servicios_editar"];
        trace?: never;
    };
    "/api/v1/servicios/cut/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Busca por nombre en los tres niveles, sin tildes ni mayúsculas. */
        get: operations["servicios_cut_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servicios/cut/codigo/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El camino inverso: de un código a la unidad territorial, con o sin ceros. */
        get: operations["servicios_cut_codigo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servicios/permisos/{patente}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El vehículo y sus permisos; una patente `PR` y cuatro dígitos, sus provisionales. */
        get: operations["servicios_permisos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El índice de la wiki, por sección y orden. Sin sesión, solo lo publicado. */
        get: operations["wiki_listar"];
        put?: never;
        /** @description El índice de la wiki, por sección y orden. Sin sesión, solo lo publicado. */
        post: operations["wiki_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Una entrada con su versión vigente. Sin versión publicada, 404. */
        get: operations["wiki_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Una entrada con su versión vigente. Sin versión publicada, 404. */
        patch: operations["wiki_editar"];
        trace?: never;
    };
    "/api/v1/wiki/{slug}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El historial de una entrada. Una edición es siempre una versión nueva, en borrador. */
        get: operations["wiki_versiones"];
        put?: never;
        /** @description El historial de una entrada. Una edición es siempre una versión nueva, en borrador. */
        post: operations["wiki_versiones_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki/{slug}/versiones/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Una versión con su Markdown y su HTML. */
        get: operations["wiki_versiones_ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki/{slug}/versiones/{version_id}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Marca una versión como vigente. Publicar una antigua es volver atrás. */
        post: operations["wiki_versiones_publicar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El perfil propio. Es lo que el frontend pide al entrar para armar la interfaz. */
        get: operations["yo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Agrupa campos planos del modelo como en la ficha. Nulo si la ficha no lo declara. */
        Acceso: {
            tipo: string;
            detalle: string;
        };
        /**
         * @description * `abierto` - Abierto
         *     * `credencial` - Con credencial
         *     * `clave-unica` - Con Clave Única
         * @enum {string}
         */
        AccesoTipoEnum: "abierto" | "credencial" | "clave-unica";
        Ambiente: {
            readonly nombre: components["schemas"]["NombreEnum"];
            /** Format: uri */
            readonly base: string;
            readonly datos: components["schemas"]["DatosEnum"];
        };
        Ambito: {
            readonly nombre: string;
            readonly orden: number;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `intercambio` - Intercambio
         *     * `plataforma` - Plataforma
         * @enum {string}
         */
        ClaseEnum: "intercambio" | "plataforma";
        ComunaDelPermiso: {
            cut: string;
            nombre: string;
        };
        /** @description `definitiva` trae el vehículo y sus permisos; `provisoria`, los provisionales. */
        ConsultaPermisos: {
            tipo: components["schemas"]["ConsultaPermisosTipoEnum"];
            vehiculo?: components["schemas"]["Vehiculo"];
            permisos?: components["schemas"]["Permiso"][];
            provisionales?: components["schemas"]["PermisoProvisional"][];
        };
        /**
         * @description * `definitiva` - definitiva
         *     * `provisoria` - provisoria
         * @enum {string}
         */
        ConsultaPermisosTipoEnum: "definitiva" | "provisoria";
        Cuota: {
            numero: number;
            monto: number;
            /** Format: date */
            fecha_pago: string;
            medio_pago: string;
        };
        CutBusqueda: {
            datos: components["schemas"]["UnidadTerritorial"][];
            origen: components["schemas"]["OrigenEnum"];
            /** Format: date-time */
            obtenido_en: string;
        };
        CutUnidad: {
            datos: components["schemas"]["UnidadTerritorial"];
            origen: components["schemas"]["OrigenEnum"];
            /** Format: date-time */
            obtenido_en: string;
        };
        /**
         * @description * `inventados` - Inventados
         *     * `reales` - Reales
         * @enum {string}
         */
        DatosEnum: "inventados" | "reales";
        DesignarEncargado: {
            /** @description Perfil activo de este municipio. */
            perfil: number;
        };
        /** @description Una entrada con su versión vigente, como HTML saneado. Sin autor. */
        Entrada: {
            /** @description Inmutable. */
            readonly slug: string;
            /** Título */
            readonly titulo: string;
            /**
             * Descripción
             * @description Para el índice.
             */
            readonly descripcion: string;
            /** Sección */
            readonly seccion: components["schemas"]["SeccionEnum"];
            readonly orden: number;
            /** @description Identificador del nodo. No es clave foránea. */
            readonly nodo: string;
            readonly publicada: boolean;
            /** Format: date-time */
            readonly publicada_en: string | null;
            readonly version: number;
            readonly html: string;
        };
        /** @description Lo que un editor escribe de una entrada. El contenido va en versiones. */
        EntradaNueva: {
            /** @description Inmutable. */
            slug: string;
            /** Título */
            titulo: string;
            /**
             * Descripción
             * @description Para el índice.
             */
            descripcion: string;
            /** @description Identificador del nodo. No es clave foránea. */
            nodo?: string;
            /** Sección */
            seccion?: components["schemas"]["SeccionEnum"] | components["schemas"]["BlankEnum"];
            orden?: number;
        };
        /** @description Lo que muestra el índice. */
        EntradaResumen: {
            /** @description Inmutable. */
            readonly slug: string;
            /** Título */
            readonly titulo: string;
            /**
             * Descripción
             * @description Para el índice.
             */
            readonly descripcion: string;
            /** Sección */
            readonly seccion: components["schemas"]["SeccionEnum"];
            readonly orden: number;
            /** @description Identificador del nodo. No es clave foránea. */
            readonly nodo: string;
            readonly publicada: boolean;
            /** Format: date-time */
            readonly publicada_en: string | null;
        };
        Especificacion: {
            /** Versión */
            readonly version: string;
            readonly formato: components["schemas"]["FormatoEnum"];
            /** @description Dentro del repositorio. Vacía: solo metadato. */
            readonly ruta: string;
            /** @description sha256 del contenido. */
            readonly huella: string;
            /** Format: date */
            readonly publicada: string | null;
            readonly commit: string;
            /**
             * Format: uri
             * @description URL del archivo tal como se leyó. Nula si el nodo publica solo metadato.
             */
            readonly archivo: string;
        };
        /**
         * @description * `disponible` - Disponible
         *     * `en_construccion` - En construcción
         *     * `deseable` - Deseable
         * @enum {string}
         */
        EstadoEnum: "disponible" | "en_construccion" | "deseable";
        /**
         * @description * `openapi-3.0` - OpenAPI 3.0
         *     * `openapi-3.1` - OpenAPI 3.1
         *     * `descripcion` - Solo metadato
         * @enum {string}
         */
        FormatoEnum: "openapi-3.0" | "openapi-3.1" | "descripcion";
        Fuente: {
            readonly id: number;
            readonly tipo: components["schemas"]["FuenteTipoEnum"];
            /** Format: uri */
            url: string;
            rama?: string;
            ruta_ficha?: string;
            activa?: boolean;
            /** @description Lo fija la primera lectura válida y no cambia después. */
            readonly nodo_identificador: string;
            readonly ultima_lectura: components["schemas"]["LecturaResumen"] | null;
            /** Format: date-time */
            readonly creado_en: string;
            /** Format: date-time */
            readonly actualizado_en: string;
        };
        FuenteDelDato: {
            dato: string;
            origen: string;
        };
        /**
         * @description * `repositorio` - Repositorio
         *     * `carga_manual` - Carga manual
         * @enum {string}
         */
        FuenteTipoEnum: "repositorio" | "carga_manual";
        Integrante: {
            readonly id: number;
            readonly run: string;
            readonly nombre: string;
            readonly rol: components["schemas"]["RolEnum"];
            readonly es_encargado: boolean;
            readonly activo: boolean;
        };
        /**
         * @description * `consulta` - El municipio consulta
         *     * `entrega` - El municipio entrega
         * @enum {string}
         */
        IntercambioEnum: "consulta" | "entrega";
        Lectura: {
            readonly id: number;
            /** Format: date-time */
            readonly creado_en: string;
            readonly commit: string;
            readonly valida: boolean;
            readonly motivo: string;
            /** @description Quién pidió leer. Nulo: la tarea programada. */
            readonly perfil: string | null;
            /** @description El YAML tal como se leyó. */
            readonly contenido: string;
        };
        LecturaResumen: {
            readonly id: number;
            /** Format: date-time */
            readonly creado_en: string;
            readonly commit: string;
            readonly valida: boolean;
            readonly motivo: string;
            /** @description Quién pidió leer. Nulo: la tarea programada. */
            readonly perfil: string | null;
        };
        /**
         * @description * `Deseable` - Deseable
         *     * `En evaluación` - En Evaluacion
         *     * `En desarrollo` - En Desarrollo
         *     * `Operativo` - Operativo
         * @enum {string}
         */
        MadurezEnum: "Deseable" | "En evaluación" | "En desarrollo" | "Operativo";
        MunicipioResumen: {
            /** Código CUT */
            cut: string;
            nombre: string;
        };
        /**
         * @description * `region` - region
         *     * `provincia` - provincia
         *     * `comuna` - comuna
         * @enum {string}
         */
        NivelEnum: "region" | "provincia" | "comuna";
        /** @description La ficha completa, agrupada como en el estándar. */
        Nodo: {
            /** @description Inmutable. */
            readonly identificador: string;
            readonly nombre: string;
            readonly sigla: string;
            readonly ambito: string;
            readonly clase: components["schemas"]["ClaseEnum"];
            /**
             * @description Vacío si es una plataforma.
             *
             *     * `consulta` - El municipio consulta
             *     * `entrega` - El municipio entrega
             */
            readonly intercambio: components["schemas"]["IntercambioEnum"];
            /** Función */
            readonly funcion: string;
            readonly madurez: components["schemas"]["MadurezEnum"];
            readonly acceso_tipo: components["schemas"]["AccesoTipoEnum"];
            readonly visibilidad: components["schemas"]["VisibilidadEnum"];
            readonly orden: number;
            /**
             * Leído en
             * Format: date-time
             */
            readonly leido_en: string;
            /** Descripción */
            readonly descripcion: string;
            /** @description Lista de nombres, como en la ficha. */
            readonly instituciones: unknown;
            readonly responsable: components["schemas"]["Responsable"];
            readonly origen: components["schemas"]["Origen"] | null;
            readonly procedencia: components["schemas"]["Procedencia"] | null;
            readonly acceso: components["schemas"]["Acceso"] | null;
            readonly ambientes: components["schemas"]["Ambiente"][];
            readonly especificacion: components["schemas"]["Especificacion"] | null;
            readonly nota_editorial: string;
            /** @description Vacío: carga manual, sin fuente verificable. */
            readonly commit: string;
        };
        /** @description Lo que muestra una tarjeta del catálogo. */
        NodoResumen: {
            /** @description Inmutable. */
            readonly identificador: string;
            readonly nombre: string;
            readonly sigla: string;
            readonly ambito: string;
            readonly clase: components["schemas"]["ClaseEnum"];
            /**
             * @description Vacío si es una plataforma.
             *
             *     * `consulta` - El municipio consulta
             *     * `entrega` - El municipio entrega
             */
            readonly intercambio: components["schemas"]["IntercambioEnum"];
            /** Función */
            readonly funcion: string;
            readonly madurez: components["schemas"]["MadurezEnum"];
            readonly acceso_tipo: components["schemas"]["AccesoTipoEnum"];
            readonly visibilidad: components["schemas"]["VisibilidadEnum"];
            readonly orden: number;
            /**
             * Leído en
             * Format: date-time
             */
            readonly leido_en: string;
        };
        /**
         * @description * `pruebas` - Pruebas
         *     * `produccion` - Producción
         * @enum {string}
         */
        NombreEnum: "pruebas" | "produccion";
        /** @description Agrupa campos planos del modelo como en la ficha. Nulo si la ficha no lo declara. */
        Origen: {
            norma: string;
            nota: string;
        };
        /**
         * @description * `fuente` - fuente
         *     * `foto` - foto
         *     * `muestra` - muestra
         * @enum {string}
         */
        OrigenEnum: "fuente" | "foto" | "muestra";
        /** @description Lo que un editor escribe de una entrada. El contenido va en versiones. */
        PatchedEntradaEditorial: {
            /** Título */
            titulo?: string;
            /**
             * Descripción
             * @description Para el índice.
             */
            descripcion?: string;
            /** @description Identificador del nodo. No es clave foránea. */
            nodo?: string;
            /** Sección */
            seccion?: components["schemas"]["SeccionEnum"] | components["schemas"]["BlankEnum"];
            orden?: number;
        };
        PatchedFuente: {
            readonly id?: number;
            readonly tipo?: components["schemas"]["FuenteTipoEnum"];
            /** Format: uri */
            url?: string;
            rama?: string;
            ruta_ficha?: string;
            activa?: boolean;
            /** @description Lo fija la primera lectura válida y no cambia después. */
            readonly nodo_identificador?: string;
            readonly ultima_lectura?: components["schemas"]["LecturaResumen"] | null;
            /** Format: date-time */
            readonly creado_en?: string;
            /** Format: date-time */
            readonly actualizado_en?: string;
        };
        /** @description Lo único que una persona edita de un nodo. */
        PatchedNodoEditorial: {
            visibilidad?: components["schemas"]["VisibilidadEnum"];
            orden?: number;
            nota_editorial?: string;
        };
        PatchedPerfil: {
            readonly id?: number;
            /** @description Con o sin puntos y guion. No se cambia después de crear. */
            run?: string;
            nombre?: string;
            rol?: components["schemas"]["RolEnum"];
            /**
             * Código CUT
             * @description Código CUT de la comuna. Vacío: persona de SUBDERE.
             */
            municipio?: string | null;
            readonly es_encargado?: boolean;
            activo?: boolean;
            /** Format: date-time */
            readonly creado_en?: string;
            /** Format: date-time */
            readonly actualizado_en?: string;
        };
        /** @description Lo que un curador escribe de un servicio. `slug` y `nodo` solo al crearlo. */
        PatchedServicioEditorial: {
            /** @description La herramienta, no el nodo. */
            nombre?: string;
            /**
             * Función
             * @description Una línea, para la tarjeta.
             */
            funcion?: string;
            /** Descripción */
            descripcion?: string;
            tareas?: string[];
            fuentes?: components["schemas"]["FuenteDelDato"][];
            estado?: components["schemas"]["EstadoEnum"];
            nota?: string;
        };
        Perfil: {
            readonly id: number;
            /** @description Con o sin puntos y guion. No se cambia después de crear. */
            run: string;
            nombre: string;
            rol?: components["schemas"]["RolEnum"];
            /**
             * Código CUT
             * @description Código CUT de la comuna. Vacío: persona de SUBDERE.
             */
            municipio?: string | null;
            readonly es_encargado: boolean;
            activo?: boolean;
            /** Format: date-time */
            readonly creado_en: string;
            /** Format: date-time */
            readonly actualizado_en: string;
        };
        Permiso: {
            anio: number;
            estado: string;
            comuna: components["schemas"]["ComunaDelPermiso"];
            monto_total: number;
            /** Format: date */
            vigente_hasta: string | null;
            cuotas: components["schemas"]["Cuota"][];
        };
        PermisoProvisional: {
            anio: number;
            semestre: number;
            comuna: components["schemas"]["ComunaDelPermiso"];
            titular: components["schemas"]["TitularEmpresa"];
            marca: string;
            modelo: string;
        };
        PermisosRespuesta: {
            datos: components["schemas"]["ConsultaPermisos"];
            origen: components["schemas"]["OrigenEnum"];
            /** Format: date-time */
            obtenido_en: string;
        };
        /** @description Agrupa campos planos del modelo como en la ficha. Nulo si la ficha no lo declara. */
        Procedencia: {
            copia: string;
            fuente: string;
            detalle: string;
        };
        Responsable: {
            organismo: string;
            equipo: string;
            /** Format: email */
            correo: string;
        };
        /**
         * @description * `lector` - Lector
         *     * `editor` - Editor
         *     * `curador` - Curador
         *     * `administrador` - Administrador
         * @enum {string}
         */
        RolEnum: "lector" | "editor" | "curador" | "administrador";
        Salud: {
            estado: string;
            version: string;
        };
        /**
         * @description * `usar_el_nodo` - Usar el nodo
         *     * `intercambios` - Intercambios
         *     * `codigos` - Códigos y datos maestros
         *     * `normas` - Marco normativo
         *     * `referencia` - Referencia
         * @enum {string}
         */
        SeccionEnum: "usar_el_nodo" | "intercambios" | "codigos" | "normas" | "referencia";
        Servicio: {
            /** @description Inmutable. */
            readonly slug: string;
            /** @description Inmutable. */
            readonly nodo: string;
            /** @description La herramienta, no el nodo. */
            readonly nombre: string;
            /**
             * Función
             * @description Una línea, para la tarjeta.
             */
            readonly funcion: string;
            /** Descripción */
            readonly descripcion: string;
            readonly tareas: string[];
            readonly fuentes: components["schemas"]["FuenteDelDato"][];
            readonly estado: components["schemas"]["EstadoEnum"];
            readonly nota: string;
            /** Format: date-time */
            readonly actualizado: string;
        };
        /** @description Lo que un curador escribe de un servicio. `slug` y `nodo` solo al crearlo. */
        ServicioNuevo: {
            /** @description Inmutable. */
            slug: string;
            /** @description Inmutable. */
            nodo: string;
            /** @description La herramienta, no el nodo. */
            nombre: string;
            /**
             * Función
             * @description Una línea, para la tarjeta.
             */
            funcion: string;
            /** Descripción */
            descripcion: string;
            tareas: string[];
            fuentes?: components["schemas"]["FuenteDelDato"][];
            estado?: components["schemas"]["EstadoEnum"];
            nota?: string;
        };
        TitularEmpresa: {
            rut: string;
            razon_social: string;
        };
        UnidadSuperior: {
            codigo: string;
            nombre: string;
        };
        /** @description Una región, provincia o comuna, con los nombres de las unidades que la contienen. */
        UnidadTerritorial: {
            nivel: components["schemas"]["NivelEnum"];
            /** @description Canónico: con los ceros a la izquierda. */
            codigo: string;
            nombre: string;
            /** @description Solo en una comuna. */
            provincia: components["schemas"]["UnidadSuperior"] | null;
            /** @description Nulo en una región. */
            region: components["schemas"]["UnidadSuperior"] | null;
        };
        Vehiculo: {
            patente: string;
            marca: string;
            modelo: string;
            anio_fabricacion: number;
            color: string;
            tipo: string;
        };
        /** @description Una versión con su Markdown y su HTML: la vista previa del editor. */
        Version: {
            readonly id: number;
            /** @description Qué cambió, para el historial. */
            readonly resumen: string;
            readonly autor: string;
            /** Format: date-time */
            readonly creado_en: string;
            readonly publicada: boolean;
            /** Format: date-time */
            readonly publicada_en: string | null;
            readonly vigente: boolean;
            readonly markdown: string;
            readonly html: string;
        };
        VersionNueva: {
            markdown: string;
            /** @description Qué cambió, para el historial. */
            resumen: string;
        };
        /** @description Una línea del historial. */
        VersionResumen: {
            readonly id: number;
            /** @description Qué cambió, para el historial. */
            readonly resumen: string;
            readonly autor: string;
            /** Format: date-time */
            readonly creado_en: string;
            readonly publicada: boolean;
            /** Format: date-time */
            readonly publicada_en: string | null;
            readonly vigente: boolean;
        };
        /**
         * @description * `publicado` - Publicado
         *     * `oculto` - Oculto
         *     * `retirado` - Retirado
         * @enum {string}
         */
        VisibilidadEnum: "publicado" | "oculto" | "retirado";
        Yo: {
            readonly id: number;
            readonly nombre: string;
            readonly rol: components["schemas"]["RolEnum"];
            readonly municipio: components["schemas"]["MunicipioResumen"] | null;
            /** @default false */
            readonly es_encargado: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ambitos_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ambito"][];
                };
            };
        };
    };
    fuentes_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fuente"][];
                };
            };
        };
    };
    fuentes_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Fuente"];
                "application/x-www-form-urlencoded": components["schemas"]["Fuente"];
                "multipart/form-data": components["schemas"]["Fuente"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fuente"];
                };
            };
        };
    };
    fuentes_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fuente"];
                };
            };
        };
    };
    fuentes_modificar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFuente"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFuente"];
                "multipart/form-data": components["schemas"]["PatchedFuente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fuente"];
                };
            };
        };
    };
    fuentes_lecturas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lectura"][];
                };
            };
        };
    };
    fuentes_sincronizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lectura"];
                };
            };
        };
    };
    municipios_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipioResumen"][];
                };
            };
        };
    };
    municipios_designar_encargado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cut: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignarEncargado"];
                "application/x-www-form-urlencoded": components["schemas"]["DesignarEncargado"];
                "multipart/form-data": components["schemas"]["DesignarEncargado"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
        };
    };
    municipios_equipo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cut: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integrante"][];
                };
            };
        };
    };
    nodos_listar: {
        parameters: {
            query?: {
                /** @description Nombre del ámbito */
                ambito?: string;
                clase?: string;
                intercambio?: string;
                madurez?: string;
                /** @description Exige sesión. Sin el parámetro, solo los publicados. */
                visibilidad?: "oculto" | "publicado" | "retirado" | "todas";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoResumen"][];
                };
            };
        };
    };
    nodos_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Nodo"];
                };
            };
        };
    };
    nodos_editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNodoEditorial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNodoEditorial"];
                "multipart/form-data": components["schemas"]["PatchedNodoEditorial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Nodo"];
                };
            };
        };
    };
    nodos_especificacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Especificacion"];
                };
            };
        };
    };
    nodos_especificacion_archivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identificador: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                    "application/json": string;
                };
            };
        };
    };
    perfiles_listar: {
        parameters: {
            query?: {
                activo?: boolean;
                /** @description Código CUT */
                municipio?: string;
                rol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"][];
                };
            };
        };
    };
    perfiles_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Perfil"];
                "application/x-www-form-urlencoded": components["schemas"]["Perfil"];
                "multipart/form-data": components["schemas"]["Perfil"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
        };
    };
    perfiles_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
        };
    };
    perfiles_modificar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPerfil"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPerfil"];
                "multipart/form-data": components["schemas"]["PatchedPerfil"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
        };
    };
    salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
        };
    };
    servicios_listar: {
        parameters: {
            query?: {
                /** @description Identificador o alias del nodo. Un oculto exige sesión. */
                nodo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"][];
                };
            };
        };
    };
    servicios_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioNuevo"];
                "application/x-www-form-urlencoded": components["schemas"]["ServicioNuevo"];
                "multipart/form-data": components["schemas"]["ServicioNuevo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedServicioEditorial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedServicioEditorial"];
                "multipart/form-data": components["schemas"]["PatchedServicioEditorial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_cut_buscar: {
        parameters: {
            query: {
                /** @description Al menos dos caracteres. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CutBusqueda"];
                };
            };
        };
    };
    servicios_cut_codigo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CutUnidad"];
                };
            };
        };
    };
    servicios_permisos: {
        parameters: {
            query?: {
                /** @description Solo para una patente definitiva. */
                desde_anio?: number;
            };
            header: {
                "X-Id-Tramite"?: string;
                /** @description El trámite que motiva la consulta. Queda en el registro de accesos. */
                "X-Procedimiento": string;
            };
            path: {
                patente: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermisosRespuesta"];
                };
            };
        };
    };
    wiki_listar: {
        parameters: {
            query?: {
                /** @description `todas` exige sesión e incluye las entradas sin publicar. */
                estado?: "publicadas" | "todas";
                /** @description Identificador o alias del nodo. */
                nodo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntradaResumen"][];
                };
            };
        };
    };
    wiki_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntradaNueva"];
                "application/x-www-form-urlencoded": components["schemas"]["EntradaNueva"];
                "multipart/form-data": components["schemas"]["EntradaNueva"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntradaResumen"];
                };
            };
        };
    };
    wiki_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entrada"];
                };
            };
        };
    };
    wiki_editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEntradaEditorial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEntradaEditorial"];
                "multipart/form-data": components["schemas"]["PatchedEntradaEditorial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntradaResumen"];
                };
            };
        };
    };
    wiki_versiones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResumen"][];
                };
            };
        };
    };
    wiki_versiones_crear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionNueva"];
                "application/x-www-form-urlencoded": components["schemas"]["VersionNueva"];
                "multipart/form-data": components["schemas"]["VersionNueva"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    wiki_versiones_ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    wiki_versiones_publicar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    yo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Yo"];
                };
            };
        };
    };
}
