# Generated by Django 5.2.18 on 2026-10-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_cargar_municipios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("run_numero", models.PositiveIntegerField(verbose_name="número del RUN")),
                ("run_dv", models.CharField(max_length=1, verbose_name="dígito verificador")),
                (
                    "run_tipo",
                    models.CharField(
                        default="RUN", max_length=10, verbose_name="tipo de identificador"
                    ),
                ),
                (
                    "sub",
                    models.CharField(
                        blank=True,
                        help_text="Subject del realm. Solo para depurar: no es llave.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("lector", "Lector"),
                            ("editor", "Editor"),
                            ("curador", "Curador"),
                            ("administrador", "Administrador"),
                        ],
                        default="lector",
                        max_length=20,
                    ),
                ),
                ("es_encargado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío: persona de SUBDERE.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles",
                        to="core.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfiles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("accion", models.CharField(max_length=100)),
                ("objeto", models.CharField(max_length=200)),
                ("antes", models.JSONField(default=dict)),
                ("despues", models.JSONField(default=dict)),
                ("nota", models.TextField(blank=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bitacora",
                        to="cuentas.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada de bitácora",
                "verbose_name_plural": "bitácora",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Acceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[("api", "Api"), ("pantalla", "Pantalla")], max_length=10
                    ),
                ),
                ("nodo", models.CharField(max_length=100)),
                ("operacion", models.CharField(max_length=100)),
                ("parametros", models.JSONField(default=dict)),
                ("procedimiento", models.CharField(blank=True, max_length=200)),
                ("id_tramite", models.CharField(blank=True, max_length=200)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("encontrado", "Encontrado"),
                            ("no_encontrado", "No Encontrado"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accesos",
                        to="cuentas.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "acceso",
                "verbose_name_plural": "accesos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.UniqueConstraint(
                fields=("run_tipo", "run_numero"), name="perfil_run_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_encargado", True)),
                fields=("municipio",),
                name="un_encargado_por_municipio",
            ),
        ),
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("es_encargado", False),
                    models.Q(("activo", True), ("municipio__isnull", False)),
                    _connector="OR",
                ),
                name="encargado_con_municipio_y_activo",
            ),
        ),
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_dv__regex", "^[0-9K]$")), name="perfil_run_dv_valido"
            ),
        ),
    ]
