# Generated by Django 5.2.18 on 2026-10-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogo", "0002_ambitos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(help_text="Inmutable.", max_length=100, unique=True)),
                (
                    "nombre",
                    models.CharField(help_text="La herramienta, no el nodo.", max_length=200),
                ),
                (
                    "funcion",
                    models.CharField(
                        help_text="Una línea, para la tarjeta.",
                        max_length=300,
                        verbose_name="función",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripción")),
                ("tareas", models.JSONField(default=list, help_text="Lista de frases.")),
                ("fuentes", models.JSONField(default=list, help_text="Lista de {dato, origen}.")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_construccion", "En construcción"),
                            ("deseable", "Deseable"),
                        ],
                        default="en_construccion",
                        max_length=20,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                (
                    "nodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios",
                        to="catalogo.nodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["nombre"],
            },
        ),
    ]
