# Generated by Django 5.2.18 on 2026-10-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fuente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("repositorio", "Repositorio"), ("carga_manual", "Carga manual")],
                        default="repositorio",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Dirección del proyecto en GitLab.", max_length=500
                    ),
                ),
                ("rama", models.CharField(default="main", max_length=200)),
                ("ruta_ficha", models.CharField(default="nodo/ficha.yaml", max_length=300)),
                ("activa", models.BooleanField(default=True)),
                (
                    "nodo_identificador",
                    models.SlugField(
                        blank=True,
                        help_text="Lo fija la primera lectura válida y no cambia después.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente",
                "verbose_name_plural": "fuentes",
                "ordering": ["nodo_identificador", "url"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("nodo_identificador", ""), _negated=True),
                        fields=("nodo_identificador",),
                        name="una_fuente_por_nodo",
                    ),
                    models.UniqueConstraint(
                        fields=("url", "rama", "ruta_ficha"), name="fuente_direccion_unica"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tipo", "repositorio"), _negated=True),
                            models.Q(("url", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="repositorio_con_url",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("commit", models.CharField(blank=True, max_length=64)),
                ("contenido", models.TextField(blank=True, help_text="El YAML tal como se leyó.")),
                ("valida", models.BooleanField()),
                ("motivo", models.TextField(blank=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lecturas",
                        to="registro.fuente",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quién pidió leer. Vacío: la tarea programada.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lecturas",
                        to="cuentas.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "lectura",
                "verbose_name_plural": "lecturas",
                "ordering": ["-creado_en", "-pk"],
            },
        ),
    ]
